# Homework 7. Naive Baysian - Spam or Ham

***Double Click here to edit this cell***

- Name: 
- Student ID: 
- Submission date: 

In [ ]:
%matplotlib inline
import numpy as np
import pandas as pd
import re
from sklearn.metrics import confusion_matrix, classification_report

In [ ]:
messages = pd.read_csv("spam_utf8.csv")

### We have 5572 text messages (747 spams or 4825 hams) 

## Problem 1 (5 pts): Most Common Words

- Use the following for word-splitting:
```
re.findall("[a-z0-9']+", text.lower()) 
```

- Find 20 most common spam words

In [ ]:
# YOUR CODE MUST BE HERE

**Your output should be like the following:**
```
[('to', 688), ('a', 376), ('call', 345), ('your', 256), ('you', 248), ('the', 205), ('2', 204), ('now', 198), ('for', 198), ('free', 196), ('or', 188), ('txt', 160), ('is', 158), ('u', 154), ('on', 143), ('4', 137), ('have', 135), ('ur', 134), ('from', 129), ('mobile', 126)]
```

- Find 20 most common ham words

In [ ]:
# YOUR CODE MUST BE HERE

**Your output should be like the following:**
```
[('i', 2116), ('you', 1783), ('to', 1514), ('the', 1087), ('a', 1040), ('u', 956), ('and', 834), ('in', 794), ('me', 733), ('my', 708), ('is', 692), ('it', 585), ('of', 513), ('for', 489), ('that', 467), ('have', 421), ('but', 414), ('so', 402), ('your', 402), ('are', 393)]
```

## Problem 2 (10 pts): My First Simplest Spam Filter

I designed a very simple spam classifer:
- If the text contains one of the spam words, it is a spam
- otherwise, it is a ham

Note that:
- Use the following for word-splitting:
```
re.findall("[a-z0-9']+", text.lower()) 
```

**For each spam words:**
```
['call']
['call', 'free']
['call', 'free', 'txt']
```
- **Compute confusion matrix, precision, recall, f1-score using all data as a test dataset**

In [ ]:
import re

class MySimplestSpamFilter(object):
    def fit(self, spam_words):
        # FILL OUT

    def predict(self, texts):
        res = []
        # FILL OUT
        return res

In [ ]:
# RUN THIS CELL
model = MySimplestSpamFilter()
model.fit(['call'])

y_pred = model.predict(texts)
y_true = messages['category']

print(confusion_matrix(y_true, y_pred, labels=['spam', 'ham']).T)
print(classification_report(y_true, y_pred, labels=['spam', 'ham']))

**YOUR OUTPUT SHOULD BE:**
```
[[ 328  218]
 [ 419 4607]]
             precision    recall  f1-score   support

       spam       0.60      0.44      0.51       747
        ham       0.92      0.95      0.94      4825

avg / total       0.87      0.89      0.88      5572
```

In [ ]:
# RUN THIS CELL
model = MySimplestSpamFilter()
model.fit(['call', 'free'])

y_pred = model.predict(texts)
y_true = messages['category']

print(confusion_matrix(y_true, y_pred, labels=['spam', 'ham']).T)
print(classification_report(y_true, y_pred, labels=['spam', 'ham']))

**YOUR OUTPUT SHOULD BE:**
```
[[ 438  265]
 [ 309 4560]]
             precision    recall  f1-score   support

       spam       0.62      0.59      0.60       747
        ham       0.94      0.95      0.94      4825

avg / total       0.89      0.90      0.90      5572
```

In [ ]:
# RUN THIS CELL
model = MySimplestSpamFilter()
model.fit(['call', 'free', 'txt'])

y_pred = model.predict(texts)
y_true = messages['category']

print(confusion_matrix(y_true, y_pred, labels=['spam', 'ham']).T)
print(classification_report(y_true, y_pred, labels=['spam', 'ham']))

**YOUR OUTPUT SHOULD BE:**
```
[[ 532  277]
 [ 215 4548]]
             precision    recall  f1-score   support

       spam       0.66      0.71      0.68       747
        ham       0.95      0.94      0.95      4825

avg / total       0.92      0.91      0.91      5572
```

## Problem 3 (5 pts): My Another Simplest Spam Filter

I designed another very simple spam classifer:
- If the text contains **all of the spam words**, it is a spam
- otherwise, it is a ham

Note that:
- Use the following for word-splitting:
```
re.findall("[a-z0-9']+", text.lower()) 
```

**For this set of spam words:**
```
['call', 'free', 'txt']
```
- **Compute confusion marix, precision, recall, f1-score using all data as a test dataset**

In [ ]:
import re

class MyAnotherSimplestSpamFilter(object):
    def fit(self, spam_words):
        self.spam_words = spam_words

    def predict(self, texts):
        res = []
        for text in texts:
            words = [word for word in re.findall("[a-z0-9']+", text.lower())] 
            if set(self.spam_words) <= set(words):
                res.append('spam')
            else:
                res.append('ham')
        return res

In [ ]:
# RUN THIS CELL
model = MyAnotherSimplestSpamFilter()
model.fit(['call', 'free', 'txt'])

y_pred = model.predict(texts)
y_true = messages['category']

print(confusion_matrix(y_true, y_pred, labels=['spam', 'ham']).T)
print(classification_report(y_true, y_pred, labels=['spam', 'ham']))

**YOUR OUTPUT SHOULD BE:**
```
[[   6    0]
 [ 741 4825]]
             precision    recall  f1-score   support

       spam       1.00      0.01      0.02       747
        ham       0.87      1.00      0.93      4825

avg / total       0.88      0.87      0.81      5572
```

## Problem 4. Discussion (5 pts)

- From the Problem 2, 3 experiments, discuss about precision and recall trade-off.
- WRITE HERE (To edit, double click this cell)


## Problem 5. SMS Spam Filter (20 pts)

- Using sklearn modules, implement your SMS spam filter
- Print confusion matrix, classification report, **f0.5 score**
- This homework will be graded based on **f0.5 score**

In [ ]:
# DO NO EDIT THIS CELL
import numpy as np

np.random.seed(0)

In [ ]:
# YOU CODE MUST BE HERE

# import whatever module as you need

# You must have 30% stratified sample from dataset for test dataset like the following:
# X_train, X_test, y_train, y_test = train_test_split(vecs, targets, stratify = targets, test_size = 0.3)


print(confusion_matrix(y_test, y_pred, labels=[1, 0]).T)
print(classification_report(y_test, y_pred, labels=[1, 0]))
beta = 0.5
print('f_{} score is {:6.2f}%'.format(beta, fbeta_score(y_test, y_pred, beta = beta)*100))

## Problem 6. MyBernoulliNaiveBayesClassifier (40 pts)

- Implement your own Bernoulli Naive Bayes Classifier

In [ ]:
class MyBernoulliNaiveBayesClassifier(object):
    def fit(self, X, Y, smoothing=1):
    # FILL OUT
        
    def predict(self, X):
        res = []
    # FILL OUT
        return res

In [ ]:
# RUN THIS CELL

import numpy as np
np.random.seed(0)
X = np.random.randint(2, size=(6, 100))
y = np.array([1, 2, 3, 3, 1, 0])
my_nbc = MyBernoulliNaiveBayesClassifier()
my_nbc.fit(X, y)

y_pred = my_nbc.predict(X)

print(confusion_matrix(y, y_pred).T)
print(classification_report(y, y_pred))

**YOUR OUTPUT MUST BE LIKE THE FOLLOWING:**
```
[[1 0 0 0]
 [0 2 0 0]
 [0 0 1 0]
 [0 0 0 2]]
             precision    recall  f1-score   support

          0       1.00      1.00      1.00         1
          1       1.00      1.00      1.00         2
          2       1.00      1.00      1.00         1
          3       1.00      1.00      1.00         2

avg / total       1.00      1.00      1.00         6
```

## Ethics:
If you cheat, you will get negatgive of the total points.
If the homework total is 22 and you cheat, you get -22.

## What to submit
- Run all cells
- Goto "File -> Print Preview"
- Print the page
- Submit in class
- No late homeworks accepted
- Your homework will be graded on the basis of correctness and programming skills

## Deadline: 6/3